### ISSUE TITLE
mosquitto python not currently exist

### ISSUE THREAD

**Issue by ghost** [kylegordon/mqtt-zabbix#1]
The Mosquitto Python module does not currently exist, can change the script to paho mqtt client. 
https://eclipse.org/paho/clients/python/

**Comment by swapper82** [comment]
This seems to still be a problem, any way possible that this could be fixed?
I have tried changing the code but im no programmer.

Changed these lines, but more needs uppdated to the paho client.
import paho.mqtt.client as paho
mqttc = paho.Client(client_id)


Got this far, but then im out of luck.

Traceback (most recent call last):
  File "./mqtt-zabbix.py", line 245, in <module>
    connect()
  File "./mqtt-zabbix.py", line 214, in connect
    result = mqttc.connect(MQTT_HOST, MQTT_PORT, 60, True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 808, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 565, in create_connection
    sock.bind(source_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: coercing to Unicode: need string or buffer, bool found

**Comment by kylegordon** [comment]
@jamestutton kindly submitted an improvement that also includes the use of Paho. I don't use this project any more, but if anyone fancies testing it and letting me know if it works, we might be able to close this issue!

**Comment by TheUserDead** [comment]
you need separately install "pip install paho-mqtt" and launch it.
*sign, al this uses Python2
